name: Build and publish python package

on:
  release:
    types: [ published ]

jobs:
  publish-service-client-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - run: poetry config pypi-token.pypi "${{ secrets.PYPI_TOKEN }}"

      - name: Publish package
        run: poetry publish --build --username __token__